name: 有虫子在机器人身上爬（悲）
about: 选这个，帮助2kbot变得更好！
title: "[BUG?!]"
labels: ["Bug?"]
assignees: ["Abjust"]

*首先，感谢你为2kbot提出意见*
- type: textarea
    id: part1
    attributes:
      label: 简明描述
      description: 简单描述下bug是怎样的
    validations:
      required: true

- type: textarea
    id: part2
    attributes:
      label: 如何重现
      description: 这个bug是怎样重现的？
      value: 我不到啊

- type: textarea
    id: what-happened
    attributes:
      label: 期望现象
      description: 你本来这么做是期望什么？
    validations:
      required: true

- type: textarea
    id: what-happened
    attributes:
      label: 补充说明
      description: 还有什么想说的吗？

- type: checkboxes
    id: terms
    attributes:
      label: 请对下列选项进行确认。
      options:
        - label: "我已经仔细阅读上述教程和 [\"《提问的智慧》\"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。"
          required: true
        - label: "我确定不是因为我技术菜乱搞才导致的。"
          required: true
        - label: "我确定这是一个有意义的Issue，且目前没有解决方案。"
          required: true
